<?php


return [

    'DashboardControllers@Dashboard' => 'general',
    'AuthControllers@login' => 'login',
    'AuthControllers@doLogin' => 'doLogin',
    'AuthControllers@logout' => 'logout',

    'UsersControllers@index' => 'list-users',
    'UsersControllers@edit' => 'edit-user',
    'UsersControllers@view' => 'view-user',
    'UsersControllers@update' => 'edit-user',
    'UsersControllers@add' => 'add-user',
    'UsersControllers@create' => 'add-user',
    'UsersControllers@delete' => 'delete-user',
    'UsersControllers@restore' => 'restore-user',

    'GroupsControllers@index' => 'list-groups',
    'GroupsControllers@edit' => 'edit-group',
    'GroupsControllers@update' => 'edit-group',
    'GroupsControllers@add' => 'add-group',
    'GroupsControllers@create' => 'add-group',
    'GroupsControllers@delete' => 'delete-group',

    'CoursesControllers@index' => 'list-courses',
    'CoursesControllers@edit' => 'edit-course',
    'CoursesControllers@view' => 'view-course',
    'CoursesControllers@update' => 'edit-course',
    'CoursesControllers@add' => 'add-course',
    'CoursesControllers@create' => 'add-course',
    'CoursesControllers@delete' => 'delete-course',
    'CoursesControllers@restore' => 'restore-course',
    'CoursesControllers@addImage' => 'add-course-image',
    'CoursesControllers@imageDelete' => 'delete-course-image',
    'CoursesControllers@deleteReview' => 'delete-course-review',

    'UniversityControllers@index' => 'list-universities',
    'UniversityControllers@edit' => 'edit-university',
    'UniversityControllers@update' => 'edit-university',
    'UniversityControllers@add' => 'add-university',
    'UniversityControllers@create' => 'add-university',
    'UniversityControllers@delete' => 'delete-university',

    'FacultyControllers@index' => 'list-faculties',
    'FacultyControllers@edit' => 'edit-faculty',
    'FacultyControllers@update' => 'edit-faculty',
    'FacultyControllers@add' => 'add-faculty',
    'FacultyControllers@create' => 'add-faculty',
    'FacultyControllers@delete' => 'delete-faculty',

    'FieldControllers@index' => 'list-fields',
    'FieldControllers@edit' => 'edit-field',
    'FieldControllers@update' => 'edit-field',
    'FieldControllers@add' => 'add-field',
    'FieldControllers@create' => 'add-field',
    'FieldControllers@delete' => 'delete-field',

    'LessonControllers@index' => 'list-lessons',
    'LessonControllers@edit' => 'edit-lesson',
    'LessonControllers@update' => 'edit-lesson',
    'LessonControllers@add' => 'add-lesson',
    'LessonControllers@create' => 'add-lesson',
    'LessonControllers@delete' => 'delete-lesson',
    'LessonControllers@uploadVideo' => 'add-lesson-video',
    'LessonControllers@removeVideo' => 'delete-lesson-video',
    'LessonControllers@addQuestion' => 'add-lesson-question',
    'LessonControllers@removeQuestion' => 'delete-lesson-question',
    'LessonControllers@addComment' => 'add-video-comment',
    'LessonControllers@removeComment' => 'delete-video-comment',

    'VariablesControllers@index' => 'list-variables',
    'VariablesControllers@edit' => 'edit-variable',
    'VariablesControllers@update' => 'edit-variable',
    'VariablesControllers@add' => 'add-variable',
    'VariablesControllers@create' => 'add-variable',
    'VariablesControllers@delete' => 'delete-variable',
    // 'BranchControllers@index' => 'list-branchs',
    // 'BranchControllers@edit' => 'edit-branch',
    // 'BranchControllers@update' => 'edit-branch',
    // 'BranchControllers@add' => 'add-branch',
    // 'BranchControllers@create' => 'add-branch',
    // 'BranchControllers@delete' => 'delete-branch',

    // 'DeptControllers@index' => 'list-depts',
    // 'DeptControllers@edit' => 'edit-dept',
    // 'DeptControllers@update' => 'edit-dept',
    // 'DeptControllers@add' => 'add-dept',
    // 'DeptControllers@create' => 'add-dept',
    // 'DeptControllers@delete' => 'delete-dept',

    // 'ManagementControllers@index' => 'list-managements',
    // 'ManagementControllers@edit' => 'edit-management',
    // 'ManagementControllers@update' => 'edit-management',
    // 'ManagementControllers@add' => 'add-management',
    // 'ManagementControllers@create' => 'add-management',
    // 'ManagementControllers@delete' => 'delete-management',

    // 'RelationControllers@index' => 'list-relations',
    // 'RelationControllers@edit' => 'edit-relation',
    // 'RelationControllers@update' => 'edit-relation',
    // 'RelationControllers@add' => 'add-relation',
    // 'RelationControllers@create' => 'add-relation',
    // 'RelationControllers@delete' => 'delete-relation',
    

];
