<?php


return [

    'DashboardControllers@Dashboard' => 'general',
    'DashboardControllers@getChartData' => 'general',
    'ChatControllers@index' => 'general',
    'ChatControllers@getOne' => 'general',
    'ChatControllers@newMessage' => 'general',
    'ChatControllers@chatWith' => 'general',
    'NotificationsControllers@index' => 'general',
    'NotificationsControllers@create' => 'general',
    'LessonControllers@comments' => 'general',
    'CommentControllers@index' => 'general',
    'CoursesControllers@movableLessons' => 'general',
    'CoursesControllers@moveVideo' => 'general',
    'CoursesControllers@sortLesson' => 'general',
    'CoursesControllers@sortVideo' => 'general',
    'CoursesControllers@getLessons' => 'general',
    'LessonControllers@removeAttachment' => 'general',
    'ChatControllers@uploadAttachment' => 'general',
    'AuthControllers@login' => 'login',
    'AuthControllers@doLogin' => 'doLogin',
    'AuthControllers@logout' => 'logout',
    'AuthControllers@register' => 'register',

    'UsersControllers@index' => 'list-users',
    'UsersControllers@edit' => 'edit-user',
    'UsersControllers@view' => 'view-user',
    'UsersControllers@update' => 'edit-user',
    'UsersControllers@add' => 'add-user',
    'UsersControllers@create' => 'add-user',
    'UsersControllers@delete' => 'delete-user',
    'UsersControllers@restore' => 'restore-user',
    'UsersControllers@getProfile' => 'update-profile',
    'UsersControllers@updateProfile' => 'update-profile',

    'GroupsControllers@index' => 'list-groups',
    'GroupsControllers@edit' => 'edit-group',
    'GroupsControllers@update' => 'edit-group',
    'GroupsControllers@add' => 'add-group',
    'GroupsControllers@create' => 'add-group',
    'GroupsControllers@delete' => 'delete-group',

    'CoursesControllers@index' => 'list-courses',
    'CoursesControllers@edit' => 'edit-course',
    'CoursesControllers@view' => 'view-course',
    'CoursesControllers@discussion' => 'view-course',
    'CoursesControllers@update' => 'edit-course',
    'CoursesControllers@addDiscussion' => 'edit-course',
    'CoursesControllers@removeDiscussion' => 'edit-course',
    'CoursesControllers@add' => 'add-course',
    'CoursesControllers@create' => 'add-course',
    'CoursesControllers@delete' => 'delete-course',
    'CoursesControllers@restore' => 'restore-course',
    'CoursesControllers@addImage' => 'add-course-image',
    'CoursesControllers@imageDelete' => 'delete-course-image',
    'CoursesControllers@deleteReview' => 'delete-course-review',
    'CoursesControllers@getUniversities' => 'get-universities',
    'CoursesControllers@getFaculties' => 'get-faculties',

    'UniversityControllers@index' => 'list-universities',
    'UniversityControllers@edit' => 'edit-university',
    'UniversityControllers@update' => 'edit-university',
    'UniversityControllers@add' => 'add-university',
    'UniversityControllers@create' => 'add-university',
    'UniversityControllers@delete' => 'delete-university',

    'FacultyControllers@index' => 'list-faculties',
    'FacultyControllers@edit' => 'edit-faculty',
    'FacultyControllers@update' => 'edit-faculty',
    'FacultyControllers@add' => 'add-faculty',
    'FacultyControllers@create' => 'add-faculty',
    'FacultyControllers@delete' => 'delete-faculty',

    'FieldControllers@index' => 'list-fields',
    'FieldControllers@edit' => 'edit-field',
    'FieldControllers@update' => 'edit-field',
    'FieldControllers@add' => 'add-field',
    'FieldControllers@create' => 'add-field',
    'FieldControllers@delete' => 'delete-field',

    'LessonControllers@index' => 'list-lessons',
    'LessonControllers@edit' => 'edit-lesson',
    'LessonControllers@update' => 'edit-lesson',
    'LessonControllers@add' => 'add-lesson',
    'LessonControllers@create' => 'add-lesson',
    'LessonControllers@delete' => 'delete-lesson',
    'LessonControllers@changeStatus' => 'change-video-status',
    'LessonControllers@uploadVideo' => 'add-lesson-video',
    'LessonControllers@uploadAttachment' => 'add-video-attachment',
    'LessonControllers@removeVideo' => 'delete-lesson-video',
    'LessonControllers@addQuestion' => 'add-lesson-question',
    'LessonControllers@removeQuestion' => 'delete-lesson-question',
    'LessonControllers@addComment' => 'add-video-comment',
    'LessonControllers@removeComment' => 'delete-video-comment',
    'LessonControllers@updateName' => 'update-video-name',

    'VariablesControllers@index' => 'list-variables',
    'VariablesControllers@edit' => 'edit-variable',
    'VariablesControllers@update' => 'edit-variable',
    'VariablesControllers@add' => 'add-variable',
    'VariablesControllers@create' => 'add-variable',
    'VariablesControllers@delete' => 'delete-variable',

    'QuizControllers@index' => 'list-quizes',
    'QuizControllers@edit' => 'edit-quiz',
    'QuizControllers@update' => 'edit-quiz',
    'QuizControllers@addQuestion' => 'edit-quiz',
    'QuizControllers@removeQuestion' => 'edit-quiz',
    'QuizControllers@add' => 'add-quiz',
    'QuizControllers@create' => 'add-quiz',
    'QuizControllers@delete' => 'delete-quiz',

    'PagesControllers@index' => 'list-pages',
    'PagesControllers@edit' => 'edit-page',
    'PagesControllers@update' => 'edit-page',
    'PagesControllers@add' => 'add-page',
    'PagesControllers@create' => 'add-page',
    'PagesControllers@delete' => 'delete-page',
    
    'RequestControllers@index' => 'list-student-requests',
    'RequestControllers@update' => 'edit-student-request',
    'RequestControllers@delete' => 'delete-student-request',

    'CourseStudentControllers@index' => 'list-course-students',

    'QuizScoresControllers@index' => 'list-quiz-scores',


];
